entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  file:
    filename: "/conf.yml"
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web